# Generated by Django 5.0.7 on 2025-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
