# Generated by Django 5.0.7 on 2025-09-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_update_at_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='server',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='server_unit',
            new_name='servings_unit',
        ),
    ]
